#include <iostream>
#include<fstream>
using namespace std;

class Text
{
public:
    Text()
    {
        content = "generated by default constructor";
    }
    Text(string filename)
    {
        ifstream in(filename);
        if(!in){
            cout << "Error opening file" << endl;
            return;
        }else{
            string line;
            while(getline(in,line)){
                content += line + "\n";
            }
        }
        in.close();
    }

    string getContent(){
        return content;
    }
private:
    string content;
};

int main()
{
    Text t("test.txt");
    cout << t.getContent() << endl;
    return 0;
}